title: UWC Changshu China Survival Guide
description: A student guide for life at UWC Changshu China
baseurl: ""
url: "https://uwc-survival-guide.pages.dev"
lang: "en"

collections:
  guides:
    output: true
    permalink: /guides/:path/
  authors:
    output: true
    permalink: /authors/:path/

defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
