title: UWC Changshu China Survival Guide
description: A student guide for life at UWC Changshu China
baseurl: "/UWC-Survival-Guide"
url: "https://united-world-college.github.io"
lang: "en"

collections:
  guides:
    output: true
    permalink: /guides/:path/

defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
